[workspace]
members = ["crates/hd-cas", "crates/hd-engine", "crates/hd-spec", "crates/hd-mount", "crates/hd-watch", "crates/hd-sandbox", "crates/hd-oci", "crates/hd-cli"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"
description = "A content-addressed, incremental container runtime"
repository = "https://github.com/omeedcs/hyperdocker"
documentation = "https://docs.rs/hd-cas"
readme = "README.md"
keywords = ["containers", "docker", "merkle-dag", "content-addressed", "devtools"]
categories = ["development-tools", "command-line-utilities"]

[workspace.dependencies]
blake3 = "1.6"
fastcdc = "3.1"
zstd = "0.13"
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2.0", features = ["serde"] }
rayon = "1.10"
tempfile = "3.15"
thiserror = "2.0"
toml = "0.8"
glob = "0.3"
fuser = "0.15"
libc = "0.2"
nix = { version = "0.29", features = ["signal", "process"] }
notify = "7.0"
reqwest = { version = "0.12", features = ["blocking"] }
tar = "0.4"
flate2 = "1.0"
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
dirs = "6.0"
