[package]
name = "hd-spec"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
hd-cas = { path = "../hd-cas" }
hd-engine = { path = "../hd-engine" }
serde.workspace = true
toml.workspace = true
glob.workspace = true
thiserror.workspace = true
blake3.workspace = true

[dev-dependencies]
tempfile.workspace = true
