[package]
name = "hd-cli"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "CLI binary for hyperdocker - the `hd` command"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "hd"
path = "src/main.rs"

[dependencies]
hd-cas = { path = "../hd-cas", version = "0.1.0" }
hd-engine = { path = "../hd-engine", version = "0.1.0" }
hd-spec = { path = "../hd-spec", version = "0.1.0" }
hd-mount = { path = "../hd-mount", version = "0.1.0" }
hd-watch = { path = "../hd-watch", version = "0.1.0" }
hd-sandbox = { path = "../hd-sandbox", version = "0.1.0" }
hd-oci = { path = "../hd-oci", version = "0.1.0" }
clap.workspace = true
dirs.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
