[package]
name = "hd-mount"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "FUSE filesystem projection from Merkle DAG for hyperdocker"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hd-cas = { path = "../hd-cas", version = "0.2.0" }
hd-engine = { path = "../hd-engine", version = "0.2.0" }
fuser.workspace = true
libc.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
