[package]
name = "hd-mount"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
hd-cas = { path = "../hd-cas" }
hd-engine = { path = "../hd-engine" }
fuser.workspace = true
libc.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
