[package]
name = "hd-oci"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "OCI image ingestion and Dockerfile translation for hyperdocker"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hd-cas = { path = "../hd-cas", version = "0.1.0" }
hd-spec = { path = "../hd-spec", version = "0.1.0" }
hd-engine = { path = "../hd-engine", version = "0.1.0" }
reqwest.workspace = true
tar.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
