[package]
name = "hd-engine"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Merkle DAG engine with incremental invalidation for hyperdocker"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hd-cas = { path = "../hd-cas", version = "0.2.0" }
blake3.workspace = true
serde.workspace = true
bincode.workspace = true
rayon.workspace = true
thiserror.workspace = true
glob.workspace = true

[dev-dependencies]
tempfile.workspace = true
